# Generated by Django 5.0.6 on 2024-12-25 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reporttemplate",
            name="allowed_user_types",
        ),
        migrations.RemoveField(
            model_name="reporttemplate",
            name="facility",
        ),
        migrations.RemoveField(
            model_name="reporttemplate",
            name="faction",
        ),
        migrations.RemoveField(
            model_name="reporttemplate",
            name="is_custom",
        ),
        migrations.RemoveField(
            model_name="reporttemplate",
            name="organization",
        ),
        migrations.AddField(
            model_name="reporttemplate",
            name="available_to",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who have access to this report",
                related_name="accessible_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reporttemplate",
            name="output_formats",
            field=models.JSONField(
                default=list,
                help_text="Allowed output formats for the report (e.g., ['csv', 'pdf', 'excel'])",
            ),
        ),
        migrations.AddField(
            model_name="reporttemplate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="generatedreport",
            name="filters_applied",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="generatedreport",
            name="generated_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generated_reports",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="generatedreport",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generated_reports",
                to="reports.reporttemplate",
            ),
        ),
        migrations.AlterField(
            model_name="reporttemplate",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_reports",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reporttemplate",
            name="description",
            field=models.TextField(
                blank=True,
                default="blah",
                help_text="Detailed description of the report",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reporttemplate",
            name="filters",
            field=models.JSONField(
                blank=True,
                help_text="Filter options for this report in JSON format",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reporttemplate",
            name="name",
            field=models.CharField(help_text="Name of the report", max_length=255),
        ),
        migrations.AlterField(
            model_name="reporttemplate",
            name="query",
            field=models.TextField(
                blank=True,
                help_text="SQL-like query or instructions for generating the report",
            ),
        ),
    ]
